
server:
  port: 8080

spring:
  application:
    name: tasks-mngr-api
  profiles:
    active: test

# Configuración de logs
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.app.invoice: DEBUG